In [126]:
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.metrics import brier_score_loss, roc_auc_score

In [127]:
from llm_unsupervised_conf.metrics import get_ece1, get_ece2, get_mce, get_nll
from llm_unsupervised_conf.plots import DATASETS_MAP

In [128]:
score_cols = [
    "base_response_avg_logprob",
    "base_response_avg_prob",
    "base_response_num_tokens",
    "base_answer_avg_logprob",
    "base_answer_avg_prob",
    "base_answer_num_tokens",
]

comp_methods = [
    "base_response_avg_prob",
    "base_answer_avg_prob",
    "consistency"
]

base_dir = Path("../outputs")

datasets = [
    "gsm8k",
    "polymath",
    "sciq",
    "trivia_qa",
    "webq",
]

models = [
    "Qwen3-0.6B",
    "Qwen3-1.7B",
    "Qwen3-4B-Thinking-2507",
    "Qwen3-8B",
    "Qwen3-14B",
]

In [129]:
def metric_row(name, scores, correct, n_bins):
    return [
        name,
        get_ece1(scores, correct, n_bins=n_bins),
        get_ece2(scores, correct, n_bins=n_bins),
        get_mce(scores, correct, n_bins=n_bins),
        get_nll(scores, correct),
        brier_score_loss(correct, scores),
        roc_auc_score(correct, scores),
    ]

In [116]:
full_df = []

rows = []
for model in models:
    for dataset in datasets:
        csv_path = base_dir / model / dataset / f"{model.lower().replace('-', '_')}_{dataset}_with_base_targets.csv"

        # If your filenames are different, replace the line above with the exact pattern.
        if not csv_path.exists():
            rows.append({
                "model": model,
                "dataset": dataset,
                "exists": False,
                "all_scores_ok": False,
                "num_rows": np.nan,
                "num_bad_rows": np.nan,
            })
            continue

        df = pd.read_csv(csv_path)
        # print(f"No. rows before {len(df)}")
        df = df[df["answer"].notna() & (df["answer"].str.strip() != "") & (df["answer"] != "")]
        # print(f"No. rows after {len(df)}")
        # display(df.head())

        missing_cols = [c for c in score_cols if c not in df.columns]
        if missing_cols:
            rows.append({
                "model": model,
                "dataset": dataset,
                "exists": True,
                "all_scores_ok": False,
                "num_rows": len(df),
                "num_bad_rows": np.nan,
                "missing_cols": missing_cols,
            })
            continue

        vals = df[score_cols].to_numpy()
        row_ok = df[score_cols].notna().all(axis=1) & np.isfinite(vals).all(axis=1)

        rows.append({
            "model": model,
            "dataset": dataset,
            "exists": True,
            "all_scores_ok": bool(row_ok.all()),
            "num_rows": len(df),
            "num_bad_rows": int((~row_ok).sum()),
            "missing_cols": None,
        })

        results = [metric_row(m, df[m], df["correct"], n_bins=12) for m in comp_methods]
        results_df = pd.DataFrame(results, columns=["method", "ECE1", "ECE2", "MCE", "NLL", "Brier", "AUROC"])
        

        results_df["model"] = model.split("/")[-1]
        results_df["dataset"] = dataset

        results_df = results_df[["model", "dataset", "method", "ECE1", "ECE2", "MCE", "NLL", "Brier", "AUROC"]]

        display(results_df)

        full_df.append(results_df)

full_df = pd.concat(full_df)

summary_df = pd.DataFrame(rows)
summary_df

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-0.6B,gsm8k,base_response_avg_prob,0.346541,0.376866,0.520339,0.767939,0.286903,0.331478
1,Qwen3-0.6B,gsm8k,base_answer_avg_prob,0.690378,0.706161,0.855786,2.263272,0.651136,0.495403
2,Qwen3-0.6B,gsm8k,consistency,0.055110,0.066317,0.132619,0.422315,0.106006,0.865107

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-0.6B,polymath,base_response_avg_prob,0.277464,0.308411,0.479430,0.777835,0.291402,0.302196
1,Qwen3-0.6B,polymath,base_answer_avg_prob,0.471811,0.501558,0.649662,1.493432,0.482037,0.484775
2,Qwen3-0.6B,polymath,consistency,0.106690,0.123699,0.241852,0.545494,0.160788,0.854580

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-0.6B,sciq,base_response_avg_prob,0.127479,0.138417,0.224376,0.716598,0.258857,0.466998
1,Qwen3-0.6B,sciq,base_answer_avg_prob,0.394750,0.415609,0.543154,3.218187,0.403542,0.413862
2,Qwen3-0.6B,sciq,consistency,0.060897,0.078820,0.171154,0.592622,0.203291,0.744757

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-0.6B,trivia_qa,base_response_avg_prob,0.112392,0.145255,0.332861,0.567971,0.189343,0.422325
1,Qwen3-0.6B,trivia_qa,base_answer_avg_prob,0.194288,0.203883,0.259227,1.734038,0.207786,0.493898
2,Qwen3-0.6B,trivia_qa,consistency,0.056389,0.061437,0.091013,0.437530,0.139708,0.787908

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-0.6B,webq,base_response_avg_prob,0.103460,0.135617,0.353469,0.546528,0.179585,0.427120
1,Qwen3-0.6B,webq,base_answer_avg_prob,0.213646,0.221052,0.353909,1.496717,0.213449,0.467495
2,Qwen3-0.6B,webq,consistency,0.115155,0.149379,0.284318,0.542837,0.180901,0.640037

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-1.7B,gsm8k,base_response_avg_prob,0.384202,0.397922,0.536497,0.670594,0.238801,0.313683
1,Qwen3-1.7B,gsm8k,base_answer_avg_prob,0.816466,0.829223,0.963663,3.019367,0.771662,0.442075
2,Qwen3-1.7B,gsm8k,consistency,0.053443,0.068804,0.192273,0.489133,0.065948,0.802053

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-1.7B,polymath,base_response_avg_prob,0.342306,0.359191,0.514698,0.681964,0.244249,0.266429
1,Qwen3-1.7B,polymath,base_answer_avg_prob,0.708154,0.729655,0.912667,2.302748,0.666849,0.461663
2,Qwen3-1.7B,polymath,consistency,0.082400,0.118109,0.280250,0.431515,0.100249,0.885415

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-1.7B,sciq,base_response_avg_prob,0.209860,0.243444,0.462878,0.775974,0.289963,0.379883
1,Qwen3-1.7B,sciq,base_answer_avg_prob,0.575284,0.598577,0.745965,3.635691,0.584738,0.402168
2,Qwen3-1.7B,sciq,consistency,0.074440,0.091385,0.161310,0.653048,0.201566,0.743264

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-1.7B,trivia_qa,base_response_avg_prob,0.184685,0.229087,0.407391,0.723844,0.264296,0.316912
1,Qwen3-1.7B,trivia_qa,base_answer_avg_prob,0.350788,0.367035,0.470300,2.406117,0.363621,0.487107
2,Qwen3-1.7B,trivia_qa,consistency,0.084277,0.091154,0.136596,0.529920,0.166097,0.835622

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-1.7B,webq,base_response_avg_prob,0.106496,0.133661,0.350539,0.683001,0.244431,0.442853
1,Qwen3-1.7B,webq,base_answer_avg_prob,0.296462,0.313587,0.401406,1.810101,0.329365,0.497287
2,Qwen3-1.7B,webq,consistency,0.128631,0.167726,0.358955,0.780098,0.233108,0.633509

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-4B-Thinking-2507,gsm8k,base_response_avg_prob,0.411903,0.415913,0.512801,0.634496,0.220985,0.466022
1,Qwen3-4B-Thinking-2507,gsm8k,base_answer_avg_prob,0.834925,0.848520,0.981168,2.980720,0.770334,0.513699
2,Qwen3-4B-Thinking-2507,gsm8k,consistency,0.033810,0.040030,0.098100,0.394653,0.043124,0.733982

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-4B-Thinking-2507,polymath,base_response_avg_prob,0.393905,0.401377,0.501930,0.656023,0.231614,0.425109
1,Qwen3-4B-Thinking-2507,polymath,base_answer_avg_prob,0.735699,0.758378,0.882878,2.022802,0.647488,0.503195
2,Qwen3-4B-Thinking-2507,polymath,consistency,0.045796,0.081846,0.268235,0.256401,0.048771,0.910389

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-4B-Thinking-2507,sciq,base_response_avg_prob,0.332048,0.347062,0.547618,0.886432,0.340151,0.447266
1,Qwen3-4B-Thinking-2507,sciq,base_answer_avg_prob,0.647490,0.661923,0.781891,4.788342,0.653617,0.417601
2,Qwen3-4B-Thinking-2507,sciq,consistency,0.091560,0.107013,0.170899,0.645574,0.199164,0.710839

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-4B-Thinking-2507,trivia_qa,base_response_avg_prob,0.263994,0.306729,0.508853,0.804508,0.302204,0.273152
1,Qwen3-4B-Thinking-2507,trivia_qa,base_answer_avg_prob,0.502053,0.524655,0.647884,3.666539,0.513202,0.563621
2,Qwen3-4B-Thinking-2507,trivia_qa,consistency,0.060261,0.067138,0.137927,0.508152,0.160426,0.847492

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-4B-Thinking-2507,webq,base_response_avg_prob,0.130527,0.152932,0.305976,0.721558,0.261611,0.438545
1,Qwen3-4B-Thinking-2507,webq,base_answer_avg_prob,0.367531,0.383750,0.523775,2.177626,0.389617,0.481887
2,Qwen3-4B-Thinking-2507,webq,consistency,0.114660,0.150849,0.288866,0.746479,0.235506,0.683110

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-8B,gsm8k,base_response_avg_prob,0.400828,0.405852,0.485506,0.617839,0.212662,0.364917
1,Qwen3-8B,gsm8k,base_answer_avg_prob,0.874685,0.885534,0.985448,4.119738,0.835545,0.438550
2,Qwen3-8B,gsm8k,consistency,0.036817,0.050328,0.134364,0.364818,0.041519,0.756257

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-8B,polymath,base_response_avg_prob,0.354633,0.365841,0.480725,0.598688,0.203294,0.340147
1,Qwen3-8B,polymath,base_answer_avg_prob,0.727052,0.749197,0.886776,2.078536,0.632318,0.605609
2,Qwen3-8B,polymath,consistency,0.047520,0.091664,0.299048,0.309235,0.052767,0.877878

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-8B,sciq,base_response_avg_prob,0.206862,0.242711,0.441292,0.732965,0.269722,0.372862
1,Qwen3-8B,sciq,base_answer_avg_prob,0.646111,0.669750,0.768803,4.356980,0.652490,0.388068
2,Qwen3-8B,sciq,consistency,0.095570,0.109283,0.183882,0.815307,0.199933,0.727603

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-8B,trivia_qa,base_response_avg_prob,0.240383,0.268573,0.420792,0.750090,0.278227,0.325024
1,Qwen3-8B,trivia_qa,base_answer_avg_prob,0.596865,0.618237,0.722690,3.952235,0.603590,0.493951
2,Qwen3-8B,trivia_qa,consistency,0.044528,0.050362,0.110976,0.501247,0.146507,0.858051

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-8B,webq,base_response_avg_prob,0.098869,0.116393,0.219751,0.705273,0.255954,0.426978
1,Qwen3-8B,webq,base_answer_avg_prob,0.372759,0.396166,0.539884,1.982037,0.406402,0.484998
2,Qwen3-8B,webq,consistency,0.164441,0.189653,0.335402,0.939086,0.257049,0.667067

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-14B,gsm8k,base_response_avg_prob,0.405176,0.408974,0.480821,0.625223,0.216370,0.450549
1,Qwen3-14B,gsm8k,base_answer_avg_prob,0.707411,0.763687,0.966070,2.720205,0.633297,0.562729
2,Qwen3-14B,gsm8k,consistency,0.038826,0.053942,0.143976,0.386071,0.043188,0.748352

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-14B,polymath,base_response_avg_prob,0.369771,0.376797,0.506570,0.623917,0.215787,0.432949
1,Qwen3-14B,polymath,base_answer_avg_prob,0.597962,0.635269,0.841524,1.403445,0.476245,0.662531
2,Qwen3-14B,polymath,consistency,0.051436,0.104649,0.299425,0.273727,0.055983,0.911644

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-14B,sciq,base_response_avg_prob,0.232768,0.254465,0.367199,0.741931,0.274123,0.424630
1,Qwen3-14B,sciq,base_answer_avg_prob,0.671711,0.693788,0.781668,4.147316,0.679176,0.362804
2,Qwen3-14B,sciq,consistency,0.109240,0.129105,0.261446,0.753745,0.195296,0.716474

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-14B,trivia_qa,base_response_avg_prob,0.260876,0.276025,0.381060,0.759512,0.282715,0.449760
1,Qwen3-14B,trivia_qa,base_answer_avg_prob,0.654186,0.680808,0.817899,4.183697,0.658587,0.482168
2,Qwen3-14B,trivia_qa,consistency,0.031992,0.046125,0.109333,0.415131,0.129973,0.871588

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-14B,webq,base_response_avg_prob,0.106758,0.139462,0.306554,0.710574,0.258507,0.411058
1,Qwen3-14B,webq,base_answer_avg_prob,0.388632,0.416866,0.584313,2.137286,0.422300,0.465877
2,Qwen3-14B,webq,consistency,0.149667,0.170950,0.302429,0.852120,0.248258,0.687650

,model,dataset,exists,all_scores_ok,num_rows,num_bad_rows,missing_cols
0,Qwen3-0.6B,gsm8k,True,True,998,0,None
1,Qwen3-0.6B,polymath,True,True,997,0,None
2,Qwen3-0.6B,sciq,True,True,970,0,None
3,Qwen3-0.6B,trivia_qa,True,True,961,0,None
4,Qwen3-0.6B,webq,True,True,582,0,None
5,Qwen3-1.7B,gsm8k,True,True,999,0,None
6,Qwen3-1.7B,polymath,True,True,1000,0,None
7,Qwen3-1.7B,sciq,True,True,1000,0,None
8,Qwen3-1.7B,trivia_qa,True,True,996,0,None
9,Qwen3-1.7B,webq,True,True,986,0,None
10,Qwen3-4B-Thinking-2507,gsm8k,True,True,1000,0,None
11,Qwen3-4B-Thinking-2507,polymath,True,True,999,0,None
12,Qwen3-4B-Thinking-2507,sciq,True,True,1000,0,None
13,Qwen3-4B-Thinking-2507,trivia_qa,True,True,997,0,None
14,Qwen3-4B-Thinking-2507,webq,True,True,1000,0,None
15,Qwen3-8B,gsm8k,True,True,999,0,None
16,Qwen3-8B,polymath,True,True,1000,0,None
17,Qwen3-8B,sciq,True,True,1000,0,None
18,Qwen3-8B,trivia_qa,True,True,985,0,None
19,Qwen3-8B,webq,True,True,993,0,None
20,Qwen3-14B,gsm8k,True,True,997,0,None
21,Qwen3-14B,polymath,True,True,996,0,None
22,Qwen3-14B,sciq,True,True,1000,0,None
23,Qwen3-14B,trivia_qa,True,True,999,0,None
24,Qwen3-14B,webq,True,True,991,0,None

In [107]:
full_df

,model,dataset,method,ECE1,ECE2,MCE,NLL,Brier,AUROC
0,Qwen3-0.6B,gsm8k,base_response_avg_prob,0.346541,0.376866,0.520339,0.767939,0.286903,0.331478
1,Qwen3-0.6B,gsm8k,base_answer_avg_prob,0.690378,0.706161,0.855786,2.263272,0.651136,0.495403
2,Qwen3-0.6B,gsm8k,consistency,0.055110,0.066317,0.132619,0.422315,0.106006,0.865107
0,Qwen3-0.6B,polymath,base_response_avg_prob,0.277464,0.308411,0.479430,0.777835,0.291402,0.302196
1,Qwen3-0.6B,polymath,base_answer_avg_prob,0.471811,0.501558,0.649662,1.493432,0.482037,0.484775
...,...,...,...,...,...,...,...,...,...
1,Qwen3-14B,trivia_qa,base_answer_avg_prob,0.654186,0.680808,0.817899,4.183697,0.658587,0.482168
2,Qwen3-14B,trivia_qa,consistency,0.031992,0.046125,0.109333,0.415131,0.129973,0.871588
0,Qwen3-14B,webq,base_response_avg_prob,0.106758,0.139462,0.306554,0.710574,0.258507,0.411058
1,Qwen3-14B,webq,base_answer_avg_prob,0.388632,0.416866,0.584313,2.137286,0.422300,0.465877
2,Qwen3-14B,webq,consistency,0.149667,0.170950,0.302429,0.852120,0.248258,0.687650

In [108]:
show_cols = ["method", "ECE2", "Brier", "AUROC"]
labels_map = {
    "base_answer_avg_prob": "Base Answer Probs.",
    "base_response_avg_prob": "Base Response Probs.",
    "consistency": "Self-consistency"
}

In [109]:
model_df = full_df[["model"]+show_cols].groupby(["model", "method"]).mean().reset_index()
model_df["method"] = [labels_map[m] for m in model_df["method"].tolist()]
model_df

                     model                method      ECE2     Brier     AUROC
0               Qwen3-0.6B    Base Answer Probs.  0.409653  0.391590  0.471087
1               Qwen3-0.6B  Base Response Probs.  0.220913  0.241218  0.390024
2               Qwen3-0.6B      Self-consistency  0.095931  0.158139  0.778478
3               Qwen3-1.7B    Base Answer Probs.  0.567615  0.543247  0.458060
4               Qwen3-1.7B  Base Response Probs.  0.272661  0.256348  0.343952
5               Qwen3-1.7B      Self-consistency  0.107435  0.153393  0.779973
6                Qwen3-14B    Base Answer Probs.  0.638084  0.573921  0.507222
7                Qwen3-14B  Base Response Probs.  0.291145  0.249500  0.433789
8                Qwen3-14B      Self-consistency  0.100954  0.134540  0.787142
9   Qwen3-4B-Thinking-2507    Base Answer Probs.  0.635445  0.594852  0.496000
10  Qwen3-4B-Thinking-2507  Base Response Probs.  0.324803  0.271313  0.410019
11  Qwen3-4B-Thinking-2507      Self-consistency  0.089375  0.137398  0.777162
12                Qwen3-8B    Base Answer Probs.  0.663777  0.626069  0.482235
13                Qwen3-8B  Base Response Probs.  0.279874  0.243972  0.365986
14                Qwen3-8B      Self-consistency  0.098258  0.139555  0.777371

In [131]:
print(model_df.to_latex(index=False, float_format="%.3f"))

\begin{tabular}{llrrr}
\toprule
model & method & ECE2 & Brier & AUROC \\
\midrule
Qwen3-0.6B & Base Answer Probs. & 0.410 & 0.392 & 0.471 \\
Qwen3-0.6B & Base Response Probs. & 0.221 & 0.241 & 0.390 \\
Qwen3-0.6B & Self-consistency & 0.096 & 0.158 & 0.778 \\
Qwen3-1.7B & Base Answer Probs. & 0.568 & 0.543 & 0.458 \\
Qwen3-1.7B & Base Response Probs. & 0.273 & 0.256 & 0.344 \\
Qwen3-1.7B & Self-consistency & 0.107 & 0.153 & 0.780 \\
Qwen3-14B & Base Answer Probs. & 0.638 & 0.574 & 0.507 \\
Qwen3-14B & Base Response Probs. & 0.291 & 0.250 & 0.434 \\
Qwen3-14B & Self-consistency & 0.101 & 0.135 & 0.787 \\
Qwen3-4B-Thinking-2507 & Base Answer Probs. & 0.635 & 0.595 & 0.496 \\
Qwen3-4B-Thinking-2507 & Base Response Probs. & 0.325 & 0.271 & 0.410 \\
Qwen3-4B-Thinking-2507 & Self-consistency & 0.089 & 0.137 & 0.777 \\
Qwen3-8B & Base Answer Probs. & 0.664 & 0.626 & 0.482 \\
Qwen3-8B & Base Response Probs. & 0.280 & 0.244 & 0.366 \\
Qwen3-8B & Self-consistency & 0.098 & 0.140 & 0.777 \\
\bottomrule
\end{tabular}

In [121]:
dataset_df = full_df[["dataset"]+show_cols].groupby(["dataset", "method"]).mean().reset_index()
dataset_df["method"] = [labels_map[m] for m in dataset_df["method"].tolist()]
dataset_df["dataset"] = [DATASETS_MAP[d] for d in dataset_df["dataset"].tolist()]
dataset_df

      dataset                method      ECE2     Brier     AUROC
0       GSM8K    Base Answer Probs.  0.806625  0.732395  0.490491
1       GSM8K  Base Response Probs.  0.401105  0.235144  0.385330
2       GSM8K      Self-consistency  0.055884  0.059957  0.781150
3    Polymath    Base Answer Probs.  0.674811  0.580987  0.543555
4    Polymath  Base Response Probs.  0.362323  0.237269  0.353366
5    Polymath      Self-consistency  0.103993  0.083712  0.887981
6        SciQ    Base Answer Probs.  0.607929  0.594712  0.396901
7        SciQ  Base Response Probs.  0.245220  0.286563  0.418328
8        SciQ      Self-consistency  0.103121  0.199850  0.728588
9   Trivia QA    Base Answer Probs.  0.478923  0.469357  0.504149
10  Trivia QA  Base Response Probs.  0.245134  0.263357  0.357435
11  Trivia QA      Self-consistency  0.063243  0.148542  0.840132
12       WebQ    Base Answer Probs.  0.346284  0.352226  0.479509
13       WebQ  Base Response Probs.  0.135613  0.240018  0.429311
14       WebQ      Self-consistency  0.165712  0.230964  0.662275

In [132]:
print(dataset_df.to_latex(index=False, float_format="%.3f"))

\begin{tabular}{llrrr}
\toprule
dataset & method & ECE2 & Brier & AUROC \\
\midrule
GSM8K & Base Answer Probs. & 0.807 & 0.732 & 0.490 \\
GSM8K & Base Response Probs. & 0.401 & 0.235 & 0.385 \\
GSM8K & Self-consistency & 0.056 & 0.060 & 0.781 \\
Polymath & Base Answer Probs. & 0.675 & 0.581 & 0.544 \\
Polymath & Base Response Probs. & 0.362 & 0.237 & 0.353 \\
Polymath & Self-consistency & 0.104 & 0.084 & 0.888 \\
SciQ & Base Answer Probs. & 0.608 & 0.595 & 0.397 \\
SciQ & Base Response Probs. & 0.245 & 0.287 & 0.418 \\
SciQ & Self-consistency & 0.103 & 0.200 & 0.729 \\
Trivia QA & Base Answer Probs. & 0.479 & 0.469 & 0.504 \\
Trivia QA & Base Response Probs. & 0.245 & 0.263 & 0.357 \\
Trivia QA & Self-consistency & 0.063 & 0.149 & 0.840 \\
WebQ & Base Answer Probs. & 0.346 & 0.352 & 0.480 \\
WebQ & Base Response Probs. & 0.136 & 0.240 & 0.429 \\
WebQ & Self-consistency & 0.166 & 0.231 & 0.662 \\
\bottomrule
\end{tabular}